### ISSUE TITLE
Need Better Examples

### ISSUE THREAD

**Issue by jason-engage** [Shopify/shopify-api-php#104]
Why provide the Cookies example using YII? Can you add framework-less examples? Any way to add all the code examples necessary to run everything on the main readme file like other shopify api plugins? Needs to be even more clear and easy for beginners and even intermediates to not waste time trying to figure it out.

**Comment by bigvanstudio** [comment]
Documentation is frustrating... really poor... 
We would have to switch to another library because Shopify is not able to provide real documentation of their own libraries... really bad. Many information about NextJS and React but nothing about PHP. 
Is it so difficult to release a FULL example/tutorial using vanilla php?
If Shopify only wants to support Node and React, It is better for the community, that Shopify says the truth and does not make us to lose our time offering other bad documented options... 
If Shopify was to offer support to other languages, do it really and not in this way.
this is very sad!.
